apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd/
- keycloak/

# Métadonnées communes
commonLabels:
  app.kubernetes.io/part-of: filou-deployment
  app.kubernetes.io/managed-by: argocd
